# This is a basic workflow to help you get started with Actions
name: Waka Readme
# Controls when the action will run. 
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  # manually run it
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme:
    name: Update this repo's Readme with the latest Metrics from wakatime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: <Catherinesjkim/Catherinsjkim>
          COMMIT_MESSAGE: Updated the Readme
          SHOW_TITLE: true
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_LINES_OF_CODE: true
          SHOW_PROFILE_VIEWS: true
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_LANGUAGE: true
          SHOW_TIMEZONE: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_SHORT_INFO: true
          SHOW_LOC_CHART: true
          
