# This is a basic workflow to help you get started with Actions

name: Update Readme with my latest coding stats

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
      # Runs at 12am IST
      - cron: '30 18 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme:
    name: Automatically update my README
    runs-on: ubuntu-latest
    steps:
      - uses: catherinesjkim/waka-readme-stats@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          SHOW_MONTHLY: "False"
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: "main"
          SHOW_TITLE: "True"
          COMMIT_MSG: "Automated Coding Activity Update :alien:"
          GH_ACTION: ${{ github.action }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_TIMEZONE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "True"
          
          
