# This is a basic workflow to help you get started with Actions
name: Waka Readme
# Controls when the action will run. 
on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme:
    name: Update this repo's Readme with the latest Metrics from wakatime
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: https://github.com/Catherinesjkim/Catherinesjkim/settings/secrets
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          GH_TOKEN: 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
          REPOSITORY: <Catherinesjkim/Catherinesjkim>
          COMMIT_MESSAGE: Updated the Readme
          SHOW_TITLE: true
          
          
